repositories {
    maven { url "https://files.minecraftforge.net/maven/" }
}

dependencies {
    modApi "dev.architectury:architectury-forge:${rootProject.architectury_version}"

    forge("net.minecraftforge:forge:${rootProject.forge_version}")
    modCompileOnly("com.simibubi.create:create-${rootProject.minecraft_version}:${rootProject.create_version_forge}:slim") { transitive = false }
    modCompileOnly("com.tterrag.registrate:Registrate:${rootProject.registrate_version_forge}")
    modImplementation("dev.engine-room.flywheel:flywheel-forge-${minecraft_version}:${flywheel_version_forge}")
    compileOnly("dev.engine-room.flywheel:flywheel-forge-api-${minecraft_version}:${flywheel_version_forge}")
    modImplementation("net.createmod.ponder:Ponder-Forge-${minecraft_version}:${ponder_version}")

    modCompileOnly("net.fabricmc:fabric-loader:${fabric_loader_version}")
    modCompileOnly("curse.maven:forge-config-api-port-fabric-547434:4583000")

    modCompileOnly("com.google.code.findbugs:findbugs:3.0.1")
    annotationProcessor(implementation("io.github.llamalad7:mixinextras-common:0.4.1"))
}

architectury {
    common("fabric", "forge")
}